average:
	python3 ./average.py
bargraph:
	python3 ./bargraph.py

linegraph:
	python3 ./linegraph.py

get_data:
	python3 ./get_data.py

get_ratios:
	python3 ./ratios.py

get_num_restarts:
	python3 ./restarts.py