average:
	python3 ./average.py
bargraph: average
	python3 ./bargraph.py

linegraph: average get_ratios
	python3 ./linegraph.py

restarts_graph:
	python3 ./restarts_graph.py

get_data:
	python3 ./get_data.py

get_ratios:
	python3 ./ratios.py

get_num_restarts:
	python3 ./restarts.py