all: energy

energy: ma mah mahRatio

mahAverage:
	python3 ./mahBargraphAverage.py

mah:
	python3 ./mahBargraph.py

ma:
	python3 ./maBargraph.py

mahRatio:
	python3 ./mahRatio.py

mahRatioAverage:
	python3 ./mahRatioAverage.py